### ISSUE TITLE
Arabic

### ISSUE THREAD

**Issue by marutosi** [naitoh/rbpdf#4]
http://www.redmine.org/issues/16040

**Comment by devopswe** [comment]
> Arabic support was fixed by rbpdf 1.18.3. please use DejaVuSans font.

Can we use which fonts another DejaVuSans like Arial etc. ? 

Could you please share me another options please. Because, DejaVuSans font sizes too big for view in single page. Can rbpdf use system fonts ?

**Comment by naitoh** [comment]
@devopswe
 
> Can we use which fonts another DejaVuSans like Arial etc. ?

I think the fonts at https://github.com/naitoh/rbpdf/tree/master/rbpdf-font/lib/fonts would work.

> Could you please share me another options please. Because, DejaVuSans font sizes too big for view in single page. 

Since rbpdf support to a subset of fonts, the size of the PDF is determined based on the number of character types used in the PDF.

> Can rbpdf use system fonts ?

If a non-embedded font is used, the system font is used.
e.g. courier, helvetica, times, symbol, zapfdingbats

See: https://github.com/naitoh/rbpdf/blob/d078d843b56c8b381ce962917c07f6c2b6a10029/example/rails/app/controllers/example055_controller.rb#L60
